export const FETCH_STORE_PRODUCTS = "FETCH_STORE_PRODUCTS";
export const SET_STORE_PRODUCTS = "SET_STORE_PRODUCTS";
export const FETCH_STORE_INFORMATION = "FETCH_STORE_INFORMATION";
export const SET_STORE_INFORMATION = "SET_STORE_INFORMATION";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const FETCH_PRODUCT_VARIANTS = "FETCH_PRODUCT_VARIANTS";
export const SET_PRODUCT_VARIANTS = "SET_PRODUCT_VARIANTS";
export const FETCH_PRODUCT_GROUP = "FETCH_PRODUCT_GROUP";
export const SET_PRODUCT_GROUP = "SET_PRODUCT_GROUP";
export const LOAD_CART = "LOAD_CART";
export const INSERT_TO_CART = "INSERT_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_CUSTOMER_DATA = "SET_CUSTOMER_DATA";

export const API_DOKAN = "API_DOKAN";   // api for dokan
export const API_WC = "API_WC";         // api for woocommerce
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
export const STORE_URL = "http://store.codemissile.com/"
